# Generated by Django 3.0.8 on 2020-11-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201121_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='add_fav',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='rem_fav',
        ),
    ]
